#!/usr/bin/env python3
"""Regenerate the Skilling brand pack.

The vector sources in ``assets/`` are the source of truth and are committed. Everything
this script writes is derived from them: rasters, the favicon set, the badge SVGs, the
contrast report, and the distributable zip.

Two stages, because they have different dependencies:

    uv run --with pillow brand/build.py
        Geometry rasters (tiles, favicons, .ico, mark PNGs, avatar) and the contrast
        report. Needs Pillow only. The contrast report needs nothing but stdlib.

    uv run --with pillow --with playwright brand/build.py --with-browser
        Also renders the text-bearing assets: README banners, social preview,
        email masthead, and the badge SVGs. These need a real browser because they need
        real Archivo, and because badge padding is measured rather than estimated.
        First run also needs: uv run --with playwright playwright install chromium

    uv run --with pillow brand/build.py --zip
        Assemble dist/skilling-brand-assets-v2.0.zip from whatever is present.

Pillow and Playwright are build-time tooling. They belong in a dependency group, never in
packages/skilling runtime deps.
"""

from __future__ import annotations

import argparse
import json
import zipfile
from pathlib import Path

ROOT = Path(__file__).parent
ASSETS = ROOT / "assets"
OUT = ROOT / "dist"
PACK = "skilling-brand-assets-v2.0"

# --- The Cut. The one geometric constant in the system. ---------------------------------
# 28x28 square at 0,4 on a 32x32 canvas, with two 4-deep, 20-long channels driven in from
# opposite sides. Bars are 8 / 4 / 4 / 4 / 8 = 28. Narrowest run is 4 units, which is 2px
# at the 16px floor.
MARK_PATH = "M0 4 H28 V12 H8 V16 H28 V32 H0 V24 H20 V20 H0 Z"
MARK_POLY = [(0, 4), (28, 4), (28, 12), (8, 12), (8, 16), (28, 16),
             (28, 32), (0, 32), (0, 24), (20, 24), (20, 20), (0, 20)]

INK = (17, 24, 39)
BUILD = (200, 255, 61)
CLOUD = (243, 245, 248)
WHITE = (255, 255, 255)

# Fields the mark may sit on. All lighter than Ink — this list is the field rule in code.
# A white mark is absent deliberately: reversed, the Cut reads as a mirrored S, tile or not.
FIELDS = {"cloud": CLOUD, "build": BUILD, "white": WHITE}


# ---------------------------------------------------------------------------------------
# Contrast — stdlib only, so the report is always regenerable
# ---------------------------------------------------------------------------------------

PALETTE = {
    "Ink": "#111827", "Signal": "#4355FF", "Build": "#C8FF3D", "Cloud": "#F3F5F8",
    "Accent": "#42D7FF", "Base": "#FFFFFF", "Graphite": "#6B7280",
    "Graphite Deep": "#5F6875", "Hairline": "#E2E6EC", "Signal 700": "#2E3FE0",
    "Signal 300": "#8B98FF", "Signal 050": "#EDEFFF", "Cyan 700": "#0E7490",
    "Void": "#0A0E17", "Slate": "#1F2937", "Verified": "#166534", "Fault": "#C2313C",
    "Verified 300": "#7EE0A0", "Fault 300": "#FF8A94",
}
BACKGROUNDS = ["Base", "Cloud", "Ink", "Void", "Slate", "Build", "Signal"]


def _linear(channel: float) -> float:
    c = channel / 255.0
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def luminance(hex_colour: str) -> float:
    h = hex_colour.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    return 0.2126 * _linear(r) + 0.7152 * _linear(g) + 0.0722 * _linear(b)


def contrast(a: str, b: str) -> float:
    la, lb = luminance(a), luminance(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def _self_check() -> None:
    """Validate the implementation against known WCAG reference pairs.

    Never skip this. The whole point of publishing ratios is that they are computed, and a
    silently wrong formula publishes confident nonsense.
    """
    for a, b, expected in (("#767676", "#FFFFFF", 4.54),
                           ("#000000", "#FFFFFF", 21.00),
                           ("#0000FF", "#FFFFFF", 8.59)):
        got = round(contrast(a, b), 2)
        if got != expected:
            raise SystemExit(f"contrast self-check failed: {a} on {b} = {got}, expected {expected}")


def _verdict(ratio: float) -> str:
    if ratio >= 7:
        return "AAA"
    if ratio >= 4.5:
        return "AA"
    return "AA-large" if ratio >= 3 else "fail"


def write_contrast_report() -> Path:
    _self_check()
    lines = [
        "# Contrast report", "",
        "Skilling brand kit v2.0. Generated by `brand/build.py` — do not hand-edit.", "",
        "Computed with the WCAG 2.x relative-luminance formula. The implementation is "
        "validated on every run against three known reference pairs: `#767676` on white = "
        "4.54:1, black on white = 21.00:1, and `#0000FF` on white = 8.59:1.", "",
        "`fail` is below 3:1. `AA-large` is 3:1–4.5:1, permitted only for text at 24px+, "
        "or 18.66px+ bold, or for non-text elements.", "",
        "## Foreground on background", "",
        "| Foreground | " + " | ".join(BACKGROUNDS) + " |",
        "|---|" + "---|" * len(BACKGROUNDS),
    ]
    for name, hexv in PALETTE.items():
        cells = []
        for bg in BACKGROUNDS:
            r = contrast(hexv, PALETTE[bg])
            cells.append(f"{r:.2f} {_verdict(r)}")
        lines.append(f"| {name} `{hexv}` | " + " | ".join(cells) + " |")

    lines += ["", "## Load-bearing pairings", "", "| Pairing | Ratio | Verdict |", "|---|---|---|"]
    for fg, bg, note in [
        ("Ink", "Base", "Default body text"),
        ("Ink", "Cloud", "Text on technical panels"),
        ("Ink", "Build", "The mark on a lime tile"),
        ("Graphite", "Cloud", "**Fails AA for small text.** Use Graphite Deep."),
        ("Graphite Deep", "Cloud", "Secondary type on Cloud"),
        ("Graphite Deep", "Base", "Passes on both — the safe default for secondary type"),
        ("Signal", "Base", "Links, compatibility chips"),
        ("Signal", "Ink", "**Fails.** Why the parent swaps its mark's unit to lime on dark."),
        ("Signal 300", "Void", "Links in dark mode"),
        ("Build", "Base", "**Fails.** Lime is a surface, never type."),
        ("Verified", "Base", "Validator pass, light"),
        ("Verified", "Void", "**Fails.** Use Verified 300."),
        ("Verified 300", "Void", "Validator pass, dark"),
        ("Fault", "Base", "Validator failure, light"),
        ("Fault", "Void", "**Fails.** Use Fault 300."),
        ("Fault 300", "Void", "Validator failure, dark"),
    ]:
        lines.append(f"| {fg} on {bg} | {contrast(PALETTE[fg], PALETTE[bg]):.2f}:1 | {note} |")

    lines += [
        "", "## Corrections to Future of Dev v1.0", "",
        "Recomputing the parent kit's published figures found four that drift. None causes a "
        "failure, but principle P3 says ratios are computed, not assumed.", "",
        "| Pairing | Published | Measured |", "|---|---|---|",
        f"| Ink on white | 16.4 | **{contrast('#111827', '#FFFFFF'):.2f}** |",
        f"| Ink on Cloud | 15.4 | **{contrast('#111827', '#F3F5F8'):.2f}** |",
        f"| Signal 700 on white | 7.0 | **{contrast('#2E3FE0', '#FFFFFF'):.2f}** |",
        f"| Cloud on Void | 18.8 | **{contrast('#F3F5F8', '#0A0E17'):.2f}** |",
        "", "## The mark is not a contrast problem", "",
        "The Cut's legibility constraint is figure–ground, not contrast. White on Ink measures "
        f"{contrast('#FFFFFF', '#111827'):.2f}:1 — an excellent ratio — and the mark is still "
        "unreadable, because at 80.1% coverage the channels are the counters, and inverting "
        "them turns the counters into strokes. No ratio can tell you that; it was found by "
        "rendering the mark and looking at it.",
    ]
    path = ASSETS / "tokens" / "contrast-report.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


# ---------------------------------------------------------------------------------------
# Geometry rasters — Pillow
# ---------------------------------------------------------------------------------------

def _tile(px: int, field, mark=INK, supersample: int = 8):
    from PIL import Image, ImageDraw
    big = Image.new("RGB", (px * supersample, px * supersample), field)
    draw = ImageDraw.Draw(big)
    k = px * supersample / 36.0          # 36x36 field, mark inset 4 on x
    draw.polygon([((x + 4) * k, y * k) for x, y in MARK_POLY], fill=mark)
    return big.resize((px, px), Image.LANCZOS)


def _bare(px: int, mark=INK, supersample: int = 8):
    from PIL import Image, ImageDraw
    big = Image.new("RGBA", (px * supersample, px * supersample), (0, 0, 0, 0))
    draw = ImageDraw.Draw(big)
    k = px * supersample / 32.0
    draw.polygon([(x * k, y * k) for x, y in MARK_POLY], fill=mark + (255,))
    return big.resize((px, px), Image.LANCZOS)


def build_rasters() -> int:
    from PIL import Image  # noqa: F401  (fail early with a clear error if absent)
    count = 0
    for name, field in FIELDS.items():
        d = ASSETS / "tiles" / "png"
        d.mkdir(parents=True, exist_ok=True)
        for size in (512, 256, 128, 64):
            _tile(size, field).save(d / f"skilling-tile-{name}-{size}.png")
            count += 1

    d = ASSETS / "mark" / "png"
    d.mkdir(parents=True, exist_ok=True)
    for size in (512, 256, 128, 64, 32):
        _bare(size).save(d / f"skilling-mark-ink-{size}.png")
        count += 1

    d = ASSETS / "favicon"
    for size in (16, 32, 48, 64):
        _tile(size, CLOUD).save(d / f"favicon-{size}.png")
        count += 1
    ico = [_tile(s, CLOUD) for s in (16, 32, 48, 64)]
    ico[0].save(d / "favicon.ico", format="ICO",
                sizes=[(16, 16), (32, 32), (48, 48), (64, 64)], append_images=ico[1:])
    count += 1
    _tile(180, BUILD).save(d / "apple-touch-icon-180.png")
    _tile(192, BUILD).save(d / "android-chrome-192.png")
    _tile(512, BUILD).save(d / "android-chrome-512.png")
    count += 3

    d = ASSETS / "github"
    d.mkdir(parents=True, exist_ok=True)
    _tile(460, BUILD).save(d / "avatar-460.png")
    _tile(460, CLOUD).save(d / "avatar-460-cloud.png")
    count += 2
    return count


# ---------------------------------------------------------------------------------------
# Text-bearing assets — Playwright, because they need real Archivo
# ---------------------------------------------------------------------------------------

FONT_LINK = ('<link href="https://fonts.googleapis.com/css2?'
             'family=Archivo:wdth,wght@62..125,100..900&'
             'family=Inter:wght@400;500;600;700&'
             'family=JetBrains+Mono:wght@400;500;700&display=swap" rel="stylesheet">')

# Every badge here states something checkable, and the unflattering ones stay.
# "independent implementations: 0" is the honest number while every row in
# docs/implementations.md shares one author — and this project's whole argument is
# that a registry of one is honest rather than impressive. Bump these by hand when
# the underlying fact changes; a badge that drifts from the repo is worse than no badge.
BADGES = [
    # label, message, message background, message text colour
    ("spec", "1.4.0-draft", "#4355FF", "#FFFFFF"),
    ("licence", "Apache-2.0", "#6B7280", "#FFFFFF"),
    ("spec text", "CC BY 4.0", "#6B7280", "#FFFFFF"),
    ("independent implementations", "0", "#6B7280", "#FFFFFF"),
    ("conformance", "self-certified", "#6B7280", "#FFFFFF"),
    ("reference runtime", "no model required", "#4355FF", "#FFFFFF"),
    ("pypi", "skilling", "#4355FF", "#FFFFFF"),
    ("built with", "Skilling", "#C8FF3D", "#111827"),
]
# shields.io convention: an SVG behind <img> cannot load a webfont, so badges use Verdana.
BADGE_FONT = "Verdana,'DejaVu Sans',Geneva,sans-serif"


def _tile_markup(size: int, field: str, fill: str = "#111827") -> str:
    k = size / 36
    return (f'<g transform="scale({k})"><rect width="36" height="36" fill="{field}"/>'
            f'<g transform="translate(4,0)"><path d="{MARK_PATH}" fill="{fill}"/></g></g>')


def build_browser_assets() -> int:
    from playwright.sync_api import sync_playwright

    import tempfile

    count = 0
    # Scratch file lives outside the tree: some mounts disallow unlink, and a stray
    # _shell.html inside dist/ would otherwise end up in the zip.
    tmpdir = Path(tempfile.mkdtemp(prefix="skilling-brand-"))
    shell = tmpdir / "_shell.html"

    with sync_playwright() as pw:
        browser = pw.chromium.launch(args=["--no-sandbox", "--disable-dev-shm-usage"])

        def render(path: Path, width: int, height: int, body: str, scale: int = 1) -> None:
            shell.write_text(
                f"<!DOCTYPE html><html><head><meta charset=utf-8>{FONT_LINK}"
                "<style>*{box-sizing:border-box}html,body{margin:0;padding:0;"
                "background:transparent}"
                ".wm{font-family:Archivo;font-weight:800;"
                "font-variation-settings:'wdth' 112,'wght' 800;letter-spacing:-.03em;"
                "line-height:1}.bd{font-family:Inter}"
                ".mo{font-family:'JetBrains Mono';font-weight:500}</style>"
                f"</head><body>{body}</body></html>", encoding="utf-8")
            page = browser.new_page(viewport={"width": width, "height": height},
                                    device_scale_factor=scale)
            page.goto(shell.as_uri())
            page.wait_for_timeout(2200)
            path.parent.mkdir(parents=True, exist_ok=True)
            page.screenshot(path=str(path), omit_background=True)
            page.close()

        # --- badges: measure the text, then emit exact-width SVGs -----------------------
        measure = browser.new_page()
        measure.set_content(f"<!DOCTYPE html><html><head>{FONT_LINK}</head>"
                            '<body><svg id="s" width="3000" height="200"></svg></body></html>')
        measure.wait_for_timeout(1500)
        strings = sorted({s for pair in BADGES for s in pair[:2]})
        widths = measure.evaluate(
            """(payload) => {
                const NS='http://www.w3.org/2000/svg';
                const svg=document.getElementById('s'); const out={};
                for(const s of payload.strings){
                  const t=document.createElementNS(NS,'text');
                  t.setAttribute('style',`font-family:${payload.font};font-size:110px`);
                  t.setAttribute('x',0); t.setAttribute('y',0);
                  t.textContent=s; svg.appendChild(t);
                  out[s]=t.getComputedTextLength()/10.0;   // width at 11px
                  t.remove();
                }
                return out;
            }""", {"strings": strings, "font": BADGE_FONT})
        measure.close()

        badge_dir = ASSETS / "github" / "badges"
        badge_dir.mkdir(parents=True, exist_ok=True)
        for label, msg, colour, text_colour in BADGES:
            lw = round(widths[label] + 10, 1)
            mw = round(widths[msg] + 10, 1)
            total, height = round(lw + mw, 1), 20
            slug = f"{label}-{msg}".lower().replace(" ", "-").replace(".", "").replace("/", "-")
            (badge_dir / f"{slug}.svg").write_text(
                '<?xml version="1.0" encoding="UTF-8"?>\n'
                f'<svg xmlns="http://www.w3.org/2000/svg" width="{total}" height="{height}" '
                f'viewBox="0 0 {total} {height}" role="img" aria-label="{label}: {msg}">\n'
                f'  <title>{label}: {msg}</title>\n'
                f'  <rect width="{lw}" height="{height}" fill="#111827"/>\n'
                f'  <rect x="{lw}" width="{mw}" height="{height}" fill="{colour}"/>\n'
                f'  <g font-family="{BADGE_FONT}" font-size="11" text-anchor="middle">\n'
                f'    <text x="{lw / 2}" y="14" fill="#FFFFFF">{label}</text>\n'
                f'    <text x="{lw + mw / 2}" y="14" fill="{text_colour}">{msg}</text>\n'
                '  </g>\n</svg>\n', encoding="utf-8")
            count += 1

        # --- README banners -------------------------------------------------------------
        def banner(dark: bool) -> str:
            bg = "#0A0E17" if dark else "#FFFFFF"
            fg = "#F3F5F8" if dark else "#111827"
            muted = "#97A1B2" if dark else "#5F6875"
            # Field rule: on a light page the page is already the field, so the mark goes
            # bare. Only the dark banner needs to carry its own.
            mark = (f'<svg width="104" height="104" viewBox="0 0 36 36">{_tile_markup(36, "#C8FF3D")}</svg>'
                    if dark else
                    f'<svg width="91" height="91" viewBox="0 0 32 32">'
                    f'<path d="{MARK_PATH}" fill="#111827"/></svg>')
            return (f'<div style="width:1280px;height:320px;background:{bg};display:flex;'
                    'align-items:center;padding:0 84px;">'
                    '<div style="display:flex;align-items:center;gap:34px;">'
                    f'{mark}'
                    '<div>'
                    # Learner-first: the benefit leads, the format is how it is delivered.
                    # Authors get the second line, never the first.
                    f'<div class="wm" style="font-size:76px;color:{fg};margin-bottom:14px;">Skilling</div>'
                    f'<div class="bd" style="font-size:21px;color:{muted};">Learn one-to-one, '
                    'with Claude Code or Codex.</div>'
                    f'<div class="mo" style="font-size:15px;color:{muted};margin-top:12px;">'
                    'Start a course · skilling 0.5.0</div>'
                    '</div></div></div>')

        gh = ASSETS / "github"
        render(gh / "readme-banner-light.png", 1280, 320, banner(False)); count += 1
        render(gh / "readme-banner-dark.png", 1280, 320, banner(True)); count += 1

        # --- social preview: GitHub requires exactly 1280x640 ----------------------------
        social = (
            '<div style="width:1280px;height:640px;background:#FFFFFF;display:flex;'
            'flex-direction:column;justify-content:space-between;padding:76px 84px;">'
            '<div style="display:flex;align-items:center;gap:26px;">'
            f'<svg width="84" height="84" viewBox="0 0 36 36">{_tile_markup(36, "#F3F5F8")}</svg>'
            '<span class="mo" style="font-size:17px;color:#5F6875;letter-spacing:.14em;'
            'text-transform:uppercase;">Open format · 1.4.0-draft</span></div>'
            '<div><div class="wm" style="font-size:150px;color:#111827;margin-bottom:26px;">'
            'Skilling</div>'
            '<div class="bd" style="font-size:34px;color:#5F6875;line-height:1.35;max-width:32ch;">'
            'Learn one-to-one with Claude Code or Codex. The course and record you earn '
            'stay yours.</div></div>'
            # The mono signature is the command, not a file extension. `.skilling` in this
            # project is a hidden state directory, not a package format — see the brand
            # kit's note on retiring the format lockup.
            # Learner-first: `start` creates the portable workspace a learner opens.
            '<div style="display:flex;align-items:center;justify-content:space-between;">'
            '<span class="mo" style="font-size:19px;color:#111827;">skilling start · 0.5.0</span>'
            '<span class="mo" style="font-size:15px;color:#5F6875;letter-spacing:.12em;'
            'text-transform:uppercase;">Created by Future of Dev</span></div></div>')
        render(gh / "social-preview-1280x640.png", 1280, 640, social); count += 1

        # --- email masthead: flat PNG on lime, so client inversion cannot touch it -------
        masthead = ('<div style="width:280px;height:44px;background:#FFFFFF;display:flex;'
                    'align-items:center;gap:14px;padding:0 4px;">'
                    f'<svg width="36" height="36" viewBox="0 0 36 36">{_tile_markup(36, "#C8FF3D")}</svg>'
                    '<span class="wm" style="font-size:30px;color:#111827;">Skilling</span></div>')
        email = ASSETS / "email"
        render(email / "masthead-lime-1x.png", 280, 44, masthead, scale=1); count += 1
        render(email / "masthead-lime-2x.png", 280, 44, masthead, scale=2); count += 1

        browser.close()

    import shutil

    shutil.rmtree(tmpdir, ignore_errors=True)  # best-effort: never fail the build on cleanup
    return count


# ---------------------------------------------------------------------------------------
# Zip
# ---------------------------------------------------------------------------------------

SKIP = {".DS_Store", "_shell.html"}


def _badge_slug(label: str, msg: str) -> str:
    return f"{label}-{msg}".lower().replace(" ", "-").replace(".", "").replace("/", "-")


def _is_stale_badge(path: Path) -> bool:
    """True for badge SVGs left over from an earlier BADGES set.

    Some mounts disallow unlink, so superseded badges can linger on disk. A badge that
    states a fact the repo no longer holds is worse than no badge, so they are excluded
    from the zip rather than trusted to have been cleaned up.
    """
    if path.suffix != ".svg" or path.parent.name != "badges":
        return False
    current = {_badge_slug(label, msg) for label, msg, _, _ in BADGES}
    return path.stem not in current


# Launch files that live in the repo root rather than under brand/, but which someone
# taking this pack to a fresh GitHub repo needs in the same download.
REPO_FILES = (
    ".github/ISSUE_TEMPLATE/config.yml",
    ".github/ISSUE_TEMPLATE/spec-ambiguity.yml",
    ".github/ISSUE_TEMPLATE/validator-bug.yml",
    ".github/ISSUE_TEMPLATE/conformance-claim.yml",
    ".github/PULL_REQUEST_TEMPLATE.md",
    "CODE_OF_CONDUCT.md",
    "SECURITY.md",
)


def build_zip() -> Path:
    OUT.mkdir(parents=True, exist_ok=True)
    target = OUT / f"{PACK}.zip"
    n = 0
    with zipfile.ZipFile(target, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        # Everything under brand/, including build.py itself — the pack should be able to
        # rebuild itself from its own contents.
        for path in sorted(ROOT.rglob("*")):
            if not path.is_file():
                continue
            if OUT in path.parents or path.name in SKIP or path.suffix == ".pyc":
                continue
            if _is_stale_badge(path):
                continue
            z.write(path, f"{PACK}/{path.relative_to(ROOT)}")
            n += 1
        # Repo furniture, namespaced so it is obvious where it belongs.
        repo_root = ROOT.parent
        for rel in REPO_FILES:
            src = repo_root / rel
            if src.is_file():
                z.write(src, f"{PACK}/repo-files/{rel}")
                n += 1
    with zipfile.ZipFile(target) as z:
        if z.testzip() is not None:
            raise SystemExit("zip integrity check failed")
    print(f"  {target.relative_to(ROOT.parent)} — {n} files, {target.stat().st_size / 1024:.0f} KB")
    return target


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--with-browser", action="store_true",
                    help="also render banners, social preview, masthead and badges")
    ap.add_argument("--zip", action="store_true", help="assemble the distributable zip")
    ap.add_argument("--only-report", action="store_true",
                    help="regenerate the contrast report and nothing else (stdlib only)")
    args = ap.parse_args()

    print("Skilling brand pack")
    report = write_contrast_report()
    print(f"  contrast report  → {report.relative_to(ROOT)} (self-check passed)")
    if args.only_report:
        return

    print(f"  geometry rasters → {build_rasters()} files")
    if args.with_browser:
        print(f"  browser assets   → {build_browser_assets()} files")
    else:
        print("  browser assets   → skipped (pass --with-browser)")
    if args.zip:
        build_zip()


if __name__ == "__main__":
    main()
