"""Generate ``docs/error-codes.md`` from the catalogue.

Forty codes maintained by hand in two places would disagree within a month, and the one
people read would be the stale one. So the document is generated, and a test fails if the
committed copy is out of date.
"""

from __future__ import annotations

import sys
from pathlib import Path

from ..conformance import CATALOGUE, Code, Severity

ERROR_CODES_PATH = "docs/error-codes.md"

_GROUPS: list[tuple[str, str, tuple[Code, ...]]] = [
    (
        "The manifest as a document",
        "Problems reading `course.yaml` at all, or with the values in it.",
        (
            Code.MANIFEST_MISSING,
            Code.MANIFEST_UNPARSEABLE,
            Code.MANIFEST_INVALID,
            Code.SPEC_VERSION_UNSUPPORTED,
            Code.SPEC_VERSION_NEWER_MINOR,
            Code.COURSE_ID_INVALID,
            Code.COURSE_VERSION_INVALID,
            Code.LICENSE_UNKNOWN,
            Code.BADGE_ID_DUPLICATE,
        ),
    ),
    (
        "Structure, across the manifest and the disk",
        "The manifest and the files under `phases/` must agree exactly, and numbering must "
        "leave no gaps.",
        (
            Code.PHASE_NUMBER_DUPLICATE,
            Code.PHASE_NUMBERING_GAP,
            Code.LESSON_NUMBER_DUPLICATE,
            Code.LESSON_NUMBERING_GAP,
            Code.LESSON_FILE_MISSING,
            Code.LESSON_FILE_ORPHAN,
            Code.FRONTMATTER_MANIFEST_MISMATCH,
            Code.HOMEWORK_DECLARATION_MISMATCH,
            Code.BADGE_UNREGISTERED,
            Code.PREREQUISITE_UNRESOLVED,
            Code.AUTHORED_COUNT,
        ),
    ),
    (
        "The lesson as a document",
        "Frontmatter, the section registry, and the grammars inside each section.",
        (
            Code.LESSON_UNPARSEABLE,
            Code.LESSON_FRONTMATTER_INVALID,
            Code.SECTION_MISSING,
            Code.SECTION_OUT_OF_ORDER,
            Code.SECTION_UNKNOWN_HEADING,
            Code.SECTION_ABSENCE_UNDECLARED,
            Code.SECTION_ABSENCE_MISSING_INTENT,
            Code.SECTION_DECLARED_PRESENT_BUT_ABSENT,
            Code.OBJECTIVES_EMPTY,
            Code.KEY_TERMS_MALFORMED,
            Code.EXERCISE_EMPTY,
            Code.QUIZ_WRONG_QUESTION_COUNT,
            Code.QUIZ_WRONG_OPTION_COUNT,
            Code.QUIZ_ANSWER_LINE_MISSING,
            Code.QUIZ_ANSWER_AMBIGUOUS,
            Code.QUIZ_ANSWER_NO_REASON,
            Code.QUIZ_QUESTION_NUMBERING,
            Code.HOMEWORK_SECTION_MALFORMED,
            Code.NEXT_UP_TOO_LONG,
        ),
    ),
    (
        "Assets",
        "References to files in `assets/`.",
        (Code.ASSET_REFERENCE_DANGLING, Code.ASSET_REFERENCE_ABSOLUTE),
    ),
    (
        "Ceremony",
        "The `ceremony` block, since spec 1.1. Templates are learner-facing, so they are held "
        "to the same rules as a lesson body.",
        (
            Code.CEREMONY_UNKNOWN_PLACEHOLDER,
            Code.CEREMONY_HIGHLIGHT_MISSING,
            Code.CEREMONY_HANDLE_MALFORMED,
        ),
    ),
    (
        "Structured objectives",
        "Addressable learning objectives, since spec 1.1; kinds and verification since 1.2. "
        "`about` steers remediation and is never evidence — a quiz settles nothing.",
        (
            Code.OBJECTIVES_DECLARED_TWICE,
            Code.OBJECTIVE_ID_DUPLICATE,
            Code.OBJECTIVE_ABOUT_INVALID,
            Code.OBJECTIVE_VERIFY_ON_KNOWLEDGE,
            Code.OBJECTIVE_CHECK_WITHOUT_VERIFY,
        ),
    ),
]

_HEADER = """\
# Error codes

<!-- Generated by `task docs` from skilling.conformance. Do not edit by hand. -->

Every finding `skilling validate` reports carries a code, a location, and an anchor into the
specification. Codes are **immutable**: never renamed, never renumbered, never reused. If a
code's meaning has to change it is retired and a new one is added, because people build CI on
these strings.

The specification itself carries no per-rule identifiers. Identifiers belong to the tool that
emits them, and version with it.

```
error  course.yaml:14  lesson-number-duplicate
       Phase 0 has two lessons numbered 4.
       → spec/course-format.md#numbering-and-structure
```

## Severities

| Severity | Meaning | Effect |
|---|---|---|
| `error` | The course does not conform | `skilling validate` exits non-zero |
| `warning` | Conforming, but probably not what was meant | Exits zero unless `--strict` |
"""

_FOOTER = """\
## Using codes in CI

```bash
skilling validate ./my-course --json
```

```json
{
  "ok": false,
  "errors": 1,
  "warnings": 0,
  "findings": [
    {
      "code": "quiz-answer-no-reason",
      "severity": "error",
      "message": "Question 2's answer names the correct option but gives no reason...",
      "path": "phases/phase-1-basics/lesson-02-going-further.md",
      "line": 61,
      "anchor": "spec/course-format.md#quick-quiz"
    }
  ]
}
```

Filter on `code`, never on `message` — messages are prose and may be reworded in a patch
release. That is the point of having codes at all.
"""


def render_error_codes() -> str:
    lines = [_HEADER]
    total = 0
    for title, blurb, codes in _GROUPS:
        lines.append(f"\n## {title}\n")
        lines.append(f"{blurb}\n")
        lines.append("| Code | Severity | What it means | Specification |")
        lines.append("|---|---|---|---|")
        for code in codes:
            entry = CATALOGUE[code]
            anchor = entry.anchor
            label = anchor.split("#", 1)[1] if "#" in anchor else anchor
            lines.append(
                f"| `{code}` | {entry.severity} | {entry.summary} | [{label}](../{anchor}) |"
            )
            total += 1
        lines.append("")

    missing = set(Code) - {c for _, _, codes in _GROUPS for c in codes}
    if missing:
        raise AssertionError(f"codes missing from the grouped catalogue: {sorted(missing)}")

    errors = sum(1 for e in CATALOGUE.values() if e.severity is Severity.ERROR)
    warnings = len(CATALOGUE) - errors
    lines.append(f"{total} codes: {errors} errors, {warnings} warnings.\n")
    lines.append(_FOOTER)
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    args = list(argv if argv is not None else sys.argv[1:])
    check = "--check" in args
    args = [a for a in args if a != "--check"]
    path = Path(args[0]) if args else Path(ERROR_CODES_PATH)

    rendered = render_error_codes()
    if check:
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
        if current != rendered:
            print(f"{path} is stale. Run: task docs", file=sys.stderr)
            return 1
        print(f"{path} is current.")
        return 0

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(rendered, encoding="utf-8")
    print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
