"""The course as authored: typed models, the loader that derives structure, lesson-body
parsing, and version-to-version comparison.

Nothing here depends on delivery, conformance, or a store — a course is just a directory
until something walks it or checks it, and this subpackage is only that directory, typed.
"""

from ._clock import next_streak, today_in, utc_now
from ._diff import DiffResult, Level, compare, compare_paths, declared_level
from ._lesson import (
    BY_HEADING,
    BY_SLOT,
    REGISTRY_ORDER,
    SECTION_REGISTRY,
    ParsedLesson,
    QuizQuestion,
    Section,
    SplitFrontmatter,
    asset_references,
    parse_homework,
    parse_lesson,
    parse_quiz,
    split_frontmatter,
    strip_code,
)
from ._loader import (
    MANIFEST_NAME,
    Course,
    CourseLoadError,
    ResolvedLesson,
    ResolvedPhase,
    discover_lesson_files,
    load_manifest,
    resolve,
)
from ._models import (
    OPTIONAL_SECTION_KEYS,
    SETTLES,
    Assignment,
    Brand,
    Capability,
    CompletionEntry,
    HomeworkArchiveEntry,
    HomeworkSlot,
    LessonFrontmatter,
    Manifest,
    Objective,
    ObjectiveMet,
    Position,
    Record,
    Requirement,
    SectionAbsence,
    Strict,
    Telemetry,
    is_course_id,
    is_semver,
)

__all__ = [
    "BY_HEADING",
    "BY_SLOT",
    "MANIFEST_NAME",
    "OPTIONAL_SECTION_KEYS",
    "REGISTRY_ORDER",
    "SECTION_REGISTRY",
    "SETTLES",
    "Assignment",
    "Brand",
    "Capability",
    "CompletionEntry",
    "Course",
    "CourseLoadError",
    "DiffResult",
    "HomeworkArchiveEntry",
    "HomeworkSlot",
    "Level",
    "LessonFrontmatter",
    "Manifest",
    "Objective",
    "ObjectiveMet",
    "ParsedLesson",
    "Position",
    "QuizQuestion",
    "Record",
    "Requirement",
    "ResolvedLesson",
    "ResolvedPhase",
    "Section",
    "SectionAbsence",
    "SplitFrontmatter",
    "Strict",
    "Telemetry",
    "asset_references",
    "compare",
    "compare_paths",
    "declared_level",
    "discover_lesson_files",
    "is_course_id",
    "is_semver",
    "load_manifest",
    "next_streak",
    "parse_homework",
    "parse_lesson",
    "parse_quiz",
    "resolve",
    "split_frontmatter",
    "strip_code",
    "today_in",
    "utc_now",
]
